### ISSUE TITLE
How to write a recipe with more than one command?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [zwegner/make.py#2]
That's my entire question.

I should note, however, that I'm not sure I need this, or even that it's a desirable feature to have. In Makefiles I've mainly (maybe only?) used any secondary commands in a recipe just to echo stuff to the screen.

**Comment by zwegner** [comment]
It's pretty simple: where you pass the command to `ctx.add_rule`, just pass a list of lists instead of one list.

Example (untested but should work):
```
cmds = [
  ['echo', 'Building f.o!'],
  ['cc', '-c', 'f.c']
]
ctx.add_rule('f.o', ['f.c'], cmds)
```

As a possibly-related side note, IMO the terseness of make.py is a really nice feature. `make` just spits way too much stuff out on the screen. There's also the `-v` option that prints out files on separate lines as they're built.

**Comment by JeffreyBenjaminBrown** [comment]
Fantastic!
