### ISSUE TITLE
Multi-target recipe: Slow build vs. unnatural code?

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [zwegner/make.py#5]
I've found two equivalent ways of doing something. One of them is more natural but slow, the other is fast but unnatural.

Currently my rules.py file contains something along these lines:

```python
def rules_for_subsmaple(ctx):

  if False: # more natural, but slow

    targets = [ f(ss,e) for ss in subsamples
			for e in enph_files ]
    ctx.add_rule(
      targets,
      [ g(e) for e in enph_files ],
      [ python, "python/subsample.py" ] )
    return targets

  if True: # fast, but unnatural

    # This builds all of the small targets
    big_target = "output/phony/subsamples"
    ctx.add_rule(
      big_target,
      [ g(e) for e in enph_files ],
      [ [ python, "python/subsample.py" ],
        [ "touch", big_target ] ] )

    # This records that the small targets depend on the big one.
    for ss in subsamples:
      for e in enph_files:
        small_target = f(ss,e)
        ctx.add_rule(
          small_target,
          [ big_target ],
          [ "touch", small_target ] ) # without this, `target` would
                     # look out of date relative to its dependencies
```

Both ways produce 64 target files.

If I build them the slow way, the first time takes a long time. The next time is much faster, but still takes a few seconds. A counter appears at 64 and counts down to 0.

If I build them the fast way, the first time again takes a long time. But in that case, when I rebuild, it takes no time at all.

Do you know why?

**Comment by zwegner** [comment]
I'm not 100% sure what your rules are doing, but I don't see anything that might be causing an issue. If I understand correctly, enph_files is the list of inputs, and f(ss, e) is the path of each output file. In both cases, subsample.py should just be called once. If anything, the first should be faster, since it doesn't need all the extra touch rules.

I don't know what might be causing the speed difference--in the first case, all 64 targets should go immediately from enqueued to completed. If there were some weird dependency issue or a bug, I'd expect the slow rebuilds to take as much time as the first. Are there other rules in play in your actual setup?

If you run it again, passing the -v and/or --no-parallel options, it might help narrow down what's going on. Alternatively, if you're able to create a minimal repro case I can run, I'll check it out. It should suffice to replace the main script with something like `[['sleep', '5'], ['touch', *output_files]]`.

**Comment by JeffreyBenjaminBrown** [comment]
I tried to make a minimal example and the problem disappeared; both methods behave identically. I'll close this because my problem must be something else. But just in case it is of interest to future historians, here's the minimal example:

First set up a folder like this:
```bash
mkdir temp
cd temp
mkdir input
for i in {a..z}; do echo $i > input/$i; done
```

Now, from the `temp/` folder created above, run `make.py` on these rules:

```python
from itertools import chain


files = ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z" ]
samples = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"]

def rules(ctx):
  natural(ctx)
  fast(ctx)

def natural(ctx):
  targets = [ "natural/" + s + "/" + f
              for s in samples
              for f in files ]
  ctx.add_rule(
    targets,
    [ "input/" + f
      for f in files ],
    [ [ "cp", "input/" + f, "natural/" + s ]
      for s in samples
      for f in files ] )

def fast(ctx):
  big_target = "fast/phony"
  ctx.add_rule(
    big_target,
    [ "input/" + f
      for f in files ],
    ( list( # turn the chain.iterable into a list
        chain.from_iterable( # concatenate the lists
          [ [ [ "mkdir", "-p", "fast/" + s ],
            [ "cp", "input/" + f, "fast/" + s ] ]
          for s in samples
          for f in files ] ) )
      + [["touch", big_target]] ) )

  for s in samples:
    for f in files:
      small_target = "fast/" + s + "/" + f
      ctx.add_rule(
        small_target,
        [ big_target ],
        [ "touch", small_target ] ) # without this `touch`, `target`
               # would look out of date relative to its dependencies
```
